package com.jarvis.common.embedding;

import java.util.List;

/**
 * Text embedding generated by an embedding provider.
 *
 * @param model model used to generate the embedding
 * @param values vector values
 * @param generationTimeMs generation time in milliseconds
 */
public record EmbeddingVector(
        String model,
        List<Double> values,
        long generationTimeMs
) {

    /**
     * Creates an immutable embedding vector.
     */
    public EmbeddingVector {
        values = values == null ? List.of() : List.copyOf(values);
    }

    /**
     * Returns vector dimension.
     *
     * @return dimension
     */
    public int dimension() {
        return values.size();
    }
}
